### ISSUE TITLE
document what is the deployment_file and improve quickstart

### ISSUE THREAD

**Issue by MalloZup** [SUSE/pacemaker-deploy#1]
Right now from the UX perspective, when I run 
``` ./deploy.py```

```
Usage:
    deploy.py create DEPLOYMENT_FILE [-q] [-f LOG_FILE] [-l LOG_LEVEL]
```

We should imho put an example of the deployment file so the user can understand it

**Comment by yandroskaos** [comment]
Defiitely, had one in a bad directory. It is anyway under specs, must make it comprehensive

**Comment by MalloZup** [comment]
@yandroskaos  to me the doc loooks good.
I would only reference the https://github.com/SUSE/pacemaker-deploy/blob/master/deployment.yaml.example in the main Readme.md so that an User can find it , without reading the layout of the git filesystems on github

**Comment by MalloZup** [comment]
i guess after https://github.com/SUSE/pacemaker-deploy/pull/3 we can close this
